// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GTKSOURCEVIEWMM_SOURCECOMPLETIONPROPOSAL_P_H
#define _GTKSOURCEVIEWMM_SOURCECOMPLETIONPROPOSAL_P_H


#include <glibmm/private/interface_p.h>

#include <glibmm/private/interface_p.h>

namespace gtksourceview
{

class SourceCompletionProposal_Class : public Glib::Interface_Class
{
public:
  typedef SourceCompletionProposal CppObjectType;
  typedef GtkSourceCompletionProposal BaseObjectType;
  typedef GtkSourceCompletionProposalIface BaseClassType;
  typedef Glib::Interface_Class CppClassParent;

  friend class SourceCompletionProposal;

  const Glib::Interface_Class& init();

  static void iface_init_function(void* g_iface, void* iface_data);

  static Glib::ObjectBase* wrap_new(GObject*);

protected:

  //Callbacks (default signal handlers):
  //These will call the *_impl member methods, which will then call the existing default signal callbacks, if any.
  //You could prevent the original default signal handlers being called by overriding the *_impl method.
  static void changed_callback(GtkSourceCompletionProposal* self);

  //Callbacks (virtual functions):
  static char* get_label_vfunc_callback(GtkSourceCompletionProposal* self);
  static char* get_markup_vfunc_callback(GtkSourceCompletionProposal* self);
  static char* get_text_vfunc_callback(GtkSourceCompletionProposal* self);
  static GdkPixbuf* get_icon_vfunc_callback(GtkSourceCompletionProposal* self);
  static char* get_info_vfunc_callback(GtkSourceCompletionProposal* self);
  static guint hash_vfunc_callback(GtkSourceCompletionProposal* self);
  static gboolean equal_vfunc_callback(GtkSourceCompletionProposal* self, GtkSourceCompletionProposal* other);
};


} // namespace gtksourceview


#endif /* _GTKSOURCEVIEWMM_SOURCECOMPLETIONPROPOSAL_P_H */

