// -*- c++ -*-
// Generated by gmmproc 2.46.1 -- DO NOT MODIFY!
#ifndef _GTKSOURCEVIEWMM_COMPLETIONWORDS_H
#define _GTKSOURCEVIEWMM_COMPLETIONWORDS_H


#include <glibmm/ustring.h>
#include <sigc++/sigc++.h>

/* completionwords.h
 *
 * Copyright (C) 2010, 2011 Krzesimir Nowak
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include <glibmm/object.h>
#include <gtksourceviewmm/completionprovider.h>


#ifndef DOXYGEN_SHOULD_SKIP_THIS
typedef struct _GtkSourceCompletionWords GtkSourceCompletionWords;
typedef struct _GtkSourceCompletionWordsClass GtkSourceCompletionWordsClass;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */


#ifndef DOXYGEN_SHOULD_SKIP_THIS
namespace Gsv
{ class CompletionWords_Class; } // namespace Gsv
#endif //DOXYGEN_SHOULD_SKIP_THIS

namespace Gsv
{
// TODO: docs needed. krnowak
/** Words completion provider.
 *
 * @newin{2,10}
 */

class CompletionWords
:
  public Glib::Object,
  public CompletionProvider
{
  
#ifndef DOXYGEN_SHOULD_SKIP_THIS

public:
  typedef CompletionWords CppObjectType;
  typedef CompletionWords_Class CppClassType;
  typedef GtkSourceCompletionWords BaseObjectType;
  typedef GtkSourceCompletionWordsClass BaseClassType;

  // noncopyable
  CompletionWords(const CompletionWords&) = delete;
  CompletionWords& operator=(const CompletionWords&) = delete;

private:  friend class CompletionWords_Class;
  static CppClassType completionwords_class_;

protected:
  explicit CompletionWords(const Glib::ConstructParams& construct_params);
  explicit CompletionWords(GtkSourceCompletionWords* castitem);

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

public:

  CompletionWords(CompletionWords&& src) noexcept;
  CompletionWords& operator=(CompletionWords&& src) noexcept;

  virtual ~CompletionWords() noexcept;

  /** Get the GType for this class, for use with the underlying GObject type system.
   */
  static GType get_type()      G_GNUC_CONST;

#ifndef DOXYGEN_SHOULD_SKIP_THIS


  static GType get_base_type() G_GNUC_CONST;
#endif

  ///Provides access to the underlying C GObject.
  GtkSourceCompletionWords*       gobj()       { return reinterpret_cast<GtkSourceCompletionWords*>(gobject_); }

  ///Provides access to the underlying C GObject.
  const GtkSourceCompletionWords* gobj() const { return reinterpret_cast<GtkSourceCompletionWords*>(gobject_); }

  ///Provides access to the underlying C instance. The caller is responsible for unrefing it. Use when directly setting fields in structs.
  GtkSourceCompletionWords* gobj_copy();

private:

  
protected:
    explicit CompletionWords(const Glib::ustring& name, const Glib::RefPtr<Gdk::Pixbuf>& icon);

public:
  /** Creates words provider with given name and icon.
   *
   * @param name Provider's name
   * @param icon Provider's icon
   *
   * @return A new CompletionWords.
   *
   * @newin{2,10}
   */
  
  static Glib::RefPtr<CompletionWords> create(const Glib::ustring& name, const Glib::RefPtr<Gdk::Pixbuf>& icon);


// TODO: think about a good method name - register is a C/C++ keyword. krnowak
 

  /** Registers this provider in given buffer.
   *
   * @param buffer A buffer which will use this provider.
   *
   * @newin{2,10}
   */
  void register_provider(const Glib::RefPtr<Gtk::TextBuffer>& buffer);

  
  /** Unregisters this provider from given buffer.
   *
   * @param buffer A buffer which will not use this provider anymore.
   *
   * @newin{2,10}
   */
  void unregister_provider(const Glib::RefPtr<Gtk::TextBuffer>& buffer);

  /** The provider name.
   *
   * @return A PropertyProxy that allows you to get or set the value of the property,
   * or receive notification when the value of the property changes.
   */
  Glib::PropertyProxy< Glib::ustring > property_name() ;

/** The provider name.
   *
   * @return A PropertyProxy_ReadOnly that allows you to get the value of the property,
   * or receive notification when the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly< Glib::ustring > property_name() const;


  /** The provider icon.
   *
   * @return A PropertyProxy that allows you to get or set the value of the property,
   * or receive notification when the value of the property changes.
   */
  Glib::PropertyProxy< Glib::RefPtr<Gdk::Pixbuf> > property_icon() ;

/** The provider icon.
   *
   * @return A PropertyProxy_ReadOnly that allows you to get the value of the property,
   * or receive notification when the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly< Glib::RefPtr<Gdk::Pixbuf> > property_icon() const;


  /** Number of proposals added in one batch.
   *
   * @return A PropertyProxy that allows you to get or set the value of the property,
   * or receive notification when the value of the property changes.
   */
  Glib::PropertyProxy< guint > property_proposals_batch_size() ;

/** Number of proposals added in one batch.
   *
   * @return A PropertyProxy_ReadOnly that allows you to get the value of the property,
   * or receive notification when the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly< guint > property_proposals_batch_size() const;


  /** Number of lines scanned in one batch.
   *
   * @return A PropertyProxy that allows you to get or set the value of the property,
   * or receive notification when the value of the property changes.
   */
  Glib::PropertyProxy< guint > property_scan_batch_size() ;

/** Number of lines scanned in one batch.
   *
   * @return A PropertyProxy_ReadOnly that allows you to get the value of the property,
   * or receive notification when the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly< guint > property_scan_batch_size() const;


  /** The minimum word size to complete.
   *
   * @return A PropertyProxy that allows you to get or set the value of the property,
   * or receive notification when the value of the property changes.
   */
  Glib::PropertyProxy< guint > property_minimum_word_size() ;

/** The minimum word size to complete.
   *
   * @return A PropertyProxy_ReadOnly that allows you to get the value of the property,
   * or receive notification when the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly< guint > property_minimum_word_size() const;


  /** The delay before initiating interactive completion.
   *
   * @return A PropertyProxy that allows you to get or set the value of the property,
   * or receive notification when the value of the property changes.
   */
  Glib::PropertyProxy< int > property_interactive_delay() ;

/** The delay before initiating interactive completion.
   *
   * @return A PropertyProxy_ReadOnly that allows you to get the value of the property,
   * or receive notification when the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly< int > property_interactive_delay() const;


  /** Provider priority.
   *
   * @return A PropertyProxy that allows you to get or set the value of the property,
   * or receive notification when the value of the property changes.
   */
  Glib::PropertyProxy< int > property_priority() ;

/** Provider priority.
   *
   * @return A PropertyProxy_ReadOnly that allows you to get the value of the property,
   * or receive notification when the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly< int > property_priority() const;


public:

public:
  //C++ methods used to invoke GTK+ virtual functions:

protected:
  //GTK+ Virtual Functions (override these to change behaviour):

  //Default Signal Handlers::


};

} /* namespace Gsv */


namespace Glib
{
  /** A Glib::wrap() method for this object.
   * 
   * @param object The C instance.
   * @param take_copy False if the result should take ownership of the C instance. True if it should take a new copy or ref.
   * @result A C++ instance that wraps this C instance.
   *
   * @relates Gsv::CompletionWords
   */
  Glib::RefPtr<Gsv::CompletionWords> wrap(GtkSourceCompletionWords* object, bool take_copy = false);
}


#endif /* _GTKSOURCEVIEWMM_COMPLETIONWORDS_H */

